name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_VERSION: 20.x

jobs:
  install:
    name: Install dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        working-directory: ./site
        run: npm ci

  lint:
    name: Lint
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        working-directory: ./site
        run: npm ci
      - name: Lint
        working-directory: ./site
        run: npm run lint

  type-check:
    name: Type Check
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        working-directory: ./site
        run: npm ci
      - name: Type Check
        working-directory: ./site
        run: npm run type-check

  test-validation:
    name: Validation tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        working-directory: ./site
        run: npm ci
      - name: Validation tests
        working-directory: ./site
        run: npm run test:validation

  ingest:
    name: Data ingestion
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        working-directory: ./site
        run: npm ci
      - name: Data ingestion
        working-directory: ./site
        run: npm run ingest
      - name: Upload ingested data
        uses: actions/upload-artifact@v4
        with:
          name: public-data
          path: site/public/
          retention-days: 1
          overwrite: true

  generate-indexes:
    name: Generate indexes
    needs: ingest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        working-directory: ./site
        run: npm ci
      - name: Download ingested data
        uses: actions/download-artifact@v4
        with:
          name: public-data
          path: site/public
      - name: Generate indexes
        working-directory: ./site
        run: npm run generate-index
      - name: Upload generated data
        uses: actions/upload-artifact@v4
        with:
          name: public-data
          path: site/public/
          retention-days: 1
          overwrite: true

  validate-data:
    name: Validate generated data
    needs: generate-indexes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        working-directory: ./site
        run: npm ci
      - name: Download generated data
        uses: actions/download-artifact@v4
        with:
          name: public-data
          path: site/public
      - name: Validate generated data
        working-directory: ./site
        run: npm run validate

  build:
    name: Build
    needs: [validate-data, lint, type-check, test-validation]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: site/package-lock.json
      - name: Install dependencies
        working-directory: ./site
        run: npm ci
      - name: Download generated data
        uses: actions/download-artifact@v4
        with:
          name: public-data
          path: site/public
      - name: Build
        working-directory: ./site
        run: npm run build
